### ISSUE TITLE
Should include common guidelines and workflow examples

### ISSUE THREAD

**Issue by rickardl** [telia-oss/terraform-module-template#6]
Right now there's always some initial friction in moving from a WIP module into a RELEASE one. I would suggest we move some of Kristians best practices and some of the common mistakes into some kind of GUIDELINES.md file, where we can refer design choices and preferences that the team has.

- Use variable names/descriptions from the official resource as much as possible.
- Not prefix all variable names with lambda_ when the this is mainly a lambda function. At least to me, lambda_ is moot when most of the variables are passed only to the lambda resource

**Comment by itsdalmo** [comment]
Second this! Should be a living document that we can collaborate on to keep things somewhat consistent between modules (which makes them easier to use also) 👍
